version: "3"

services:
  backend:
    container_name: car-exhibitions-backend
    build: .
    command: /bin/sh -c "/backend/entrypoint.sh"

    restart: always
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    networks:
      - car-exhibitions-net

  frontend:
    build:
      context: ./frontend
    container_name: car-exhibitions-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}
    volumes:
      - ./frontend:/frontend 
    networks:
      - car-exhibitions-net

networks:
  car-exhibitions-net:
    driver: bridge

    