version: "3"

services:
  web:
    container_name: exhibitions_cms
    build: .
    command: >
      /bin/sh -c "poetry run python manage.py makemigrations &&
                  poetry run python manage.py migrate &&
                  poetry run python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/exhibitions
    ports:
      - "8000:8000"
    networks:
      - exhibitions-cms-net

networks:
  exhibitions-cms-net:
    driver: bridge