# Generated by Django 4.2.7 on 2023-11-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("address", models.TextField()),
                ("contact_details", models.TextField()),
            ],
        ),
    ]
