# Generated by Django 4.2.7 on 2023-11-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="exhibition_covers/"
            ),
        ),
    ]
