# Generated by Django 4.2.7 on 2023-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitions", "0002_exhibition_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
