# Generated by Django 4.2.7 on 2023-11-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_exhibition_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='address',
            field=models.TextField(help_text='Address of the exhibition.'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='contact_details',
            field=models.TextField(help_text='Contact details for the exhibition.'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the exhibition.', null=True, upload_to='exhibition_covers/'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='end_date',
            field=models.DateField(help_text='End date of the exhibition.'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_date',
            field=models.DateField(help_text='Start date of the exhibition.'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='summary',
            field=models.TextField(help_text='Summary of the exhibition.'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, help_text='Ticket price for the exhibition.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(help_text='Title of the exhibition.', max_length=255),
        ),
    ]
