# Generated by Django 4.2.7 on 2023-11-20 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("address", models.TextField()),
                ("contact_details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="car_images/")),
                ("year_manufacture", models.PositiveIntegerField()),
                (
                    "engine_displacement",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("horsepower", models.PositiveIntegerField()),
                ("additional_features", models.TextField(blank=True, null=True)),
                (
                    "exhibition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.exhibition",
                    ),
                ),
            ],
        ),
    ]
