# Generated by Django 4.2.7 on 2023-11-20 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitions", "0001_initial"),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="exhibition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="exhibitions.exhibition",
            ),
        ),
        migrations.DeleteModel(
            name="Exhibition",
        ),
    ]
