# Generated by Django 4.2.7 on 2023-11-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0004_alter_exhibition_address_and_more'),
        ('cars', '0002_alter_car_exhibition_delete_exhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='additional_features',
            field=models.TextField(blank=True, help_text='Additional features of the car.', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(help_text='Description of the car.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_displacement',
            field=models.DecimalField(decimal_places=2, help_text='Engine displacement of the car in liters.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='exhibition',
            field=models.ForeignKey(help_text='Exhibition to which the car belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='exhibitions.exhibition'),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.PositiveIntegerField(help_text='Horsepower of the car.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(help_text='Image of the car.', upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(help_text='Name of the car.', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_manufacture',
            field=models.PositiveIntegerField(help_text='Year of manufacture of the car.'),
        ),
    ]
